In [77]:
import pandas as pd
from pathlib import Path

# To merge different annotator files into one

In [1]:
import pandas as pd

lisa = pd.read_csv("gollnerlisa.csv")
julian = pd.read_csv("admin.csv")
thea = pd.read_csv("Werewolf22.csv")

In [2]:
thea

,id,text,unique_id,doc_id,sentence_index,meta/previous_utterance,meta/following_utterance,label/0
0,1,No.,krajisnik_Public_Transcript_of_Hearing_09_June...,NaN,0,And this portion of the minutes of that sessio...,"And in the section sentence, Mr. Krajisnik, wh...",none
1,2,I don't know what this man wrote here but I ca...,krajisnik_Public_Transcript_of_Hearing_09_June...,NaN,1,And this portion of the minutes of that sessio...,"And in the section sentence, Mr. Krajisnik, wh...",agency
2,3,And the man here says that the political leade...,krajisnik_Public_Transcript_of_Hearing_09_June...,NaN,2,And this portion of the minutes of that sessio...,"And in the section sentence, Mr. Krajisnik, wh...",none
3,4,It was just divided into two halves.,krajisnik_Public_Transcript_of_Hearing_09_June...,NaN,3,And this portion of the minutes of that sessio...,"And in the section sentence, Mr. Krajisnik, wh...",none
4,5,I remember there was a quarrel and I said to t...,krajisnik_Public_Transcript_of_Hearing_09_June...,NaN,4,And this portion of the minutes of that sessio...,"And in the section sentence, Mr. Krajisnik, wh...",agency
...,...,...,...,...,...,...,...,...
581,582,It's the result of a request that I made.,prlic_and_others_Public_Transcript_of_Hearing_...,NaN,0,Can you please clarify what this document is a...,"If we look at item 1, at paragraph 1 of this d...",agency
582,583,"The date we see is the 8th of November, 1993.",prlic_and_others_Public_Transcript_of_Hearing_...,NaN,1,Can you please clarify what this document is a...,"If we look at item 1, at paragraph 1 of this d...",none
583,584,"Mate Boban, the Commander-in-Chief, relieves m...",prlic_and_others_Public_Transcript_of_Hearing_...,NaN,2,Can you please clarify what this document is a...,"If we look at item 1, at paragraph 1 of this d...",externalization
584,585,All the information is there.,prlic_and_others_Public_Transcript_of_Hearing_...,NaN,3,Can you please clarify what this document is a...,"If we look at item 1, at paragraph 1 of this d...",none
585,586,He hereby appoints Colonel Ante Roso as my rep...,prlic_and_others_Public_Transcript_of_Hearing_...,NaN,4,Can you please clarify what this document is a...,"If we look at item 1, at paragraph 1 of this d...",none

In [3]:
julian.head()

,id,text,unique_id,doc_id,sentence_index,meta/previous_utterance,meta/following_utterance,label/0
0,1,No.,krajisnik_Public_Transcript_of_Hearing_09_June...,NaN,0,And this portion of the minutes of that sessio...,"And in the section sentence, Mr. Krajisnik, wh...",none
1,2,I don't know what this man wrote here but I ca...,krajisnik_Public_Transcript_of_Hearing_09_June...,NaN,1,And this portion of the minutes of that sessio...,"And in the section sentence, Mr. Krajisnik, wh...",agency
2,3,And the man here says that the political leade...,krajisnik_Public_Transcript_of_Hearing_09_June...,NaN,2,And this portion of the minutes of that sessio...,"And in the section sentence, Mr. Krajisnik, wh...",none
3,4,It was just divided into two halves.,krajisnik_Public_Transcript_of_Hearing_09_June...,NaN,3,And this portion of the minutes of that sessio...,"And in the section sentence, Mr. Krajisnik, wh...",none
4,5,I remember there was a quarrel and I said to t...,krajisnik_Public_Transcript_of_Hearing_09_June...,NaN,4,And this portion of the minutes of that sessio...,"And in the section sentence, Mr. Krajisnik, wh...",agency

In [4]:
lisa.head()

,id,text,unique_id,doc_id,sentence_index,meta/previous_utterance,meta/following_utterance,label/0
0,176,No.,krajisnik_Public_Transcript_of_Hearing_09_June...,NaN,0,And this portion of the minutes of that sessio...,"And in the section sentence, Mr. Krajisnik, wh...",none
1,177,I don't know what this man wrote here but I ca...,krajisnik_Public_Transcript_of_Hearing_09_June...,NaN,1,And this portion of the minutes of that sessio...,"And in the section sentence, Mr. Krajisnik, wh...",agency
2,178,And the man here says that the political leade...,krajisnik_Public_Transcript_of_Hearing_09_June...,NaN,2,And this portion of the minutes of that sessio...,"And in the section sentence, Mr. Krajisnik, wh...",none
3,179,It was just divided into two halves.,krajisnik_Public_Transcript_of_Hearing_09_June...,NaN,3,And this portion of the minutes of that sessio...,"And in the section sentence, Mr. Krajisnik, wh...",none
4,180,I remember there was a quarrel and I said to t...,krajisnik_Public_Transcript_of_Hearing_09_June...,NaN,4,And this portion of the minutes of that sessio...,"And in the section sentence, Mr. Krajisnik, wh...",agency

In [5]:
same_columns = (
    thea.columns.equals(julian.columns) and
    thea.columns.equals(lisa.columns)
)

print("\nIdentical columns:", same_columns)

Identical columns: True

In [6]:
thea.columns

Index(['id', 'text', 'unique_id', 'doc_id', 'sentence_index',
       'meta/previous_utterance', 'meta/following_utterance', 'label/0'],
      dtype='object')

In [7]:
# Columns to remove
cols_to_drop = [
    "doc_id",
    "meta/previous_utterance",
    "meta/following_utterance"
]

# Clean all three DataFrames
for df in [thea, julian, lisa]:
    df.drop(columns=cols_to_drop, inplace=True)
    df.rename(columns={"label/0": "label"}, inplace=True)

In [8]:
def rename_label(df, annotator):
    """Rename the label column to include the annotator's name."""
    return df.rename(columns={"label": f"label_{annotator}"})

In [9]:
lisa

,id,text,unique_id,sentence_index,label
0,176,No.,krajisnik_Public_Transcript_of_Hearing_09_June...,0,none
1,177,I don't know what this man wrote here but I ca...,krajisnik_Public_Transcript_of_Hearing_09_June...,1,agency
2,178,And the man here says that the political leade...,krajisnik_Public_Transcript_of_Hearing_09_June...,2,none
3,179,It was just divided into two halves.,krajisnik_Public_Transcript_of_Hearing_09_June...,3,none
4,180,I remember there was a quarrel and I said to t...,krajisnik_Public_Transcript_of_Hearing_09_June...,4,agency
...,...,...,...,...,...
581,757,It's the result of a request that I made.,prlic_and_others_Public_Transcript_of_Hearing_...,0,agency
582,758,"The date we see is the 8th of November, 1993.",prlic_and_others_Public_Transcript_of_Hearing_...,1,none
583,759,"Mate Boban, the Commander-in-Chief, relieves m...",prlic_and_others_Public_Transcript_of_Hearing_...,2,none
584,760,All the information is there.,prlic_and_others_Public_Transcript_of_Hearing_...,3,none
585,761,He hereby appoints Colonel Ante Roso as my rep...,prlic_and_others_Public_Transcript_of_Hearing_...,4,none

In [10]:
julian

,id,text,unique_id,sentence_index,label
0,1,No.,krajisnik_Public_Transcript_of_Hearing_09_June...,0,none
1,2,I don't know what this man wrote here but I ca...,krajisnik_Public_Transcript_of_Hearing_09_June...,1,agency
2,3,And the man here says that the political leade...,krajisnik_Public_Transcript_of_Hearing_09_June...,2,none
3,4,It was just divided into two halves.,krajisnik_Public_Transcript_of_Hearing_09_June...,3,none
4,5,I remember there was a quarrel and I said to t...,krajisnik_Public_Transcript_of_Hearing_09_June...,4,agency
...,...,...,...,...,...
581,582,It's the result of a request that I made.,prlic_and_others_Public_Transcript_of_Hearing_...,0,agency
582,583,"The date we see is the 8th of November, 1993.",prlic_and_others_Public_Transcript_of_Hearing_...,1,none
583,584,"Mate Boban, the Commander-in-Chief, relieves m...",prlic_and_others_Public_Transcript_of_Hearing_...,2,none
584,585,All the information is there.,prlic_and_others_Public_Transcript_of_Hearing_...,3,none
585,586,He hereby appoints Colonel Ante Roso as my rep...,prlic_and_others_Public_Transcript_of_Hearing_...,4,none

In [11]:
thea

,id,text,unique_id,sentence_index,label
0,1,No.,krajisnik_Public_Transcript_of_Hearing_09_June...,0,none
1,2,I don't know what this man wrote here but I ca...,krajisnik_Public_Transcript_of_Hearing_09_June...,1,agency
2,3,And the man here says that the political leade...,krajisnik_Public_Transcript_of_Hearing_09_June...,2,none
3,4,It was just divided into two halves.,krajisnik_Public_Transcript_of_Hearing_09_June...,3,none
4,5,I remember there was a quarrel and I said to t...,krajisnik_Public_Transcript_of_Hearing_09_June...,4,agency
...,...,...,...,...,...
581,582,It's the result of a request that I made.,prlic_and_others_Public_Transcript_of_Hearing_...,0,agency
582,583,"The date we see is the 8th of November, 1993.",prlic_and_others_Public_Transcript_of_Hearing_...,1,none
583,584,"Mate Boban, the Commander-in-Chief, relieves m...",prlic_and_others_Public_Transcript_of_Hearing_...,2,externalization
584,585,All the information is there.,prlic_and_others_Public_Transcript_of_Hearing_...,3,none
585,586,He hereby appoints Colonel Ante Roso as my rep...,prlic_and_others_Public_Transcript_of_Hearing_...,4,none

In [16]:
from functools import reduce
import pandas as pd

def merge_annotations(dfs):
    """
    Merge annotation DataFrames on all columns except 'label' and 'id'.
    Creates a separate label column for each annotator.
    """

    # Merge on all columns except label and id
    merge_cols = [
        col for col in next(iter(dfs.values())).columns
        if col not in ["label", "id"]
    ]

    renamed_dfs = []

    for name, df in dfs.items():
        temp = (
            df.drop(columns="id")
              .rename(columns={"label": f"label_{name}"})
        )
        renamed_dfs.append(temp)

    # Merge all DataFrames
    merged = reduce(
        lambda left, right: pd.merge(
            left,
            right,
            on=merge_cols,
            how="inner"
        ),
        renamed_dfs
    )

    return merged

In [17]:
df_merged = merge_annotations({
    "lisa": lisa,
    "julian": julian,
    "thea": thea
})

In [18]:
df_merged

,text,unique_id,sentence_index,label_lisa,label_julian,label_thea
0,No.,krajisnik_Public_Transcript_of_Hearing_09_June...,0,none,none,none
1,I don't know what this man wrote here but I ca...,krajisnik_Public_Transcript_of_Hearing_09_June...,1,agency,agency,agency
2,And the man here says that the political leade...,krajisnik_Public_Transcript_of_Hearing_09_June...,2,none,none,none
3,It was just divided into two halves.,krajisnik_Public_Transcript_of_Hearing_09_June...,3,none,none,none
4,I remember there was a quarrel and I said to t...,krajisnik_Public_Transcript_of_Hearing_09_June...,4,agency,agency,agency
...,...,...,...,...,...,...
581,It's the result of a request that I made.,prlic_and_others_Public_Transcript_of_Hearing_...,0,agency,agency,agency
582,"The date we see is the 8th of November, 1993.",prlic_and_others_Public_Transcript_of_Hearing_...,1,none,none,none
583,"Mate Boban, the Commander-in-Chief, relieves m...",prlic_and_others_Public_Transcript_of_Hearing_...,2,none,none,externalization
584,All the information is there.,prlic_and_others_Public_Transcript_of_Hearing_...,3,none,none,none
585,He hereby appoints Colonel Ante Roso as my rep...,prlic_and_others_Public_Transcript_of_Hearing_...,4,none,none,none

In [19]:
df_merged.to_csv("merged_annotations.csv", encoding="utf-8", index=False)